uploads = []
outputs = []

[[generated]]
id = "RW3NapdDEB1-3CV0mft0T"
uri = "file://artifacts/veloura/assets/images/icon.png"
type = "image"
title = "veloura icon"

[[generated]]
id = "Bx2IlOZX_6XseS3RvzVFd"
uri = "file://artifacts/veloura/assets/images/wardrobe-hero.png"
type = "image"
title = "wardrobe hero"

[[generated]]
id = "uiDBtf8wx4qD2uIYQIaWI"
uri = "file://artifacts/veloura/assets/images/onboarding-hero.png"
type = "image"
title = "onboarding hero"

[[generated]]
id = "Vbagrrp5I1Bv_qlRDY9_n"
uri = "file://artifacts/veloura/assets/images/insp-brunch.png"
type = "image"
title = "Brunch Chic"

[[generated]]
id = "gQHnRGyykYid8P91oVLP0"
uri = "file://artifacts/veloura/assets/images/insp-boardroom.png"
type = "image"
title = "Boardroom Power"

[[generated]]
id = "ob1YWSyjTDU5Yt1N5n-KZ"
uri = "file://artifacts/veloura/assets/images/insp-gallery.png"
type = "image"
title = "Gallery Opening"

[[generated]]
id = "p6_3l03RrtSgM0pseTF5h"
uri = "file://artifacts/veloura/assets/images/insp-wanderer.png"
type = "image"
title = "City Wanderer"

[[generated]]
id = "jAG6XOU6LPCneHyzyxixh"
uri = "file://artifacts/veloura/assets/images/insp-garden.png"
type = "image"
title = "Garden Party"

[[generated]]
id = "6TWj3UpDK8y8N1Had0Mrl"
uri = "file://artifacts/veloura/assets/images/insp-sunday.png"
type = "image"
title = "Sunday Errands"

[[generated]]
id = "6SGvlSGY8-xBN6FBvopIq"
uri = "file://artifacts/veloura/assets/images/insp-coffee.png"
type = "image"
title = "Coffee Run"

[[generated]]
id = "AuUakrIThGqvU5QdApj4q"
uri = "file://artifacts/veloura/assets/images/insp-park.png"
type = "image"
title = "Park Stroll"

[[generated]]
id = "2AMbK8xB3aDo2laAcoKer"
uri = "file://artifacts/veloura/assets/images/insp-creative.png"
type = "image"
title = "Creative Director"

[[generated]]
id = "k_0AeDS9V0pHaYNDXFrDc"
uri = "file://artifacts/veloura/assets/images/insp-lunch.png"
type = "image"
title = "Client Lunch"

[[generated]]
id = "2WEjNMJcq1APIRQZ1x8M-"
uri = "file://artifacts/veloura/assets/images/insp-drinks.png"
type = "image"
title = "Desk to Drinks"

[[generated]]
id = "3ujsFs8Qs2VtUaiHgzyFh"
uri = "file://artifacts/veloura/assets/images/insp-wine.png"
type = "image"
title = "Wine Bar"

[[generated]]
id = "GXtZP8OEVT8KgCPmLYt2y"
uri = "file://artifacts/veloura/assets/images/insp-rooftop.png"
type = "image"
title = "Rooftop Dinner"

[[generated]]
id = "YDO6PLmS50le86ICpKxlj"
uri = "file://artifacts/veloura/assets/images/insp-cocktail.png"
type = "image"
title = "Cocktail Hour"

[[generated]]
id = "M6JVVw6TgfSW0rzAJG7vW"
uri = "file://artifacts/veloura/assets/images/insp-velvet.png"
type = "image"
title = "Velvet Soirée"
